name: paymentsapp
description: "project for payments"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  circular_chart_flutter: ^0.0.2
  intl: ^0.19.0
  image: ^4.1.3
  share: ^2.0.4
  path_provider: ^2.1.1
  delayed_display: ^2.0.0
  http: ^1.2.0
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.2.1
  responsive_grid_list: ^1.4.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.0.0

  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  provider: ^6.1.2
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  flutter_icons:
    android: true
    ios: true
    image_path: "assets/billetera.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
