// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVAGXxaxUR805pO9ddiLTPJouQPUyq9JQ',
    appId: '1:219119315316:web:29f5cc43e3a8ec5ee62421',
    messagingSenderId: '219119315316',
    projectId: 'payments-85f81',
    authDomain: 'payments-85f81.firebaseapp.com',
    databaseURL: 'https://payments-85f81-default-rtdb.firebaseio.com',
    storageBucket: 'payments-85f81.appspot.com',
    measurementId: 'G-T76DJZFQL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_V8frJ5nraDgRet2D0iI80PuybKrlFfM',
    appId: '1:219119315316:android:061df17d1276627de62421',
    messagingSenderId: '219119315316',
    projectId: 'payments-85f81',
    databaseURL: 'https://payments-85f81-default-rtdb.firebaseio.com',
    storageBucket: 'payments-85f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfRe5HJBMqvdDj7VCnsdG4Dl38O68Oh-U',
    appId: '1:219119315316:ios:4eefc9183d310d09e62421',
    messagingSenderId: '219119315316',
    projectId: 'payments-85f81',
    databaseURL: 'https://payments-85f81-default-rtdb.firebaseio.com',
    storageBucket: 'payments-85f81.appspot.com',
    iosBundleId: 'com.softdecom.paymentsapp',
  );

}